from Utils.recursiveDeleteArticles import recursiveDeleteArticles
fromt Utils.countFilesInSubDirs import txtFileCountInSubdirectories

txtFileCountInSubdirectories()
recursiveDeleteArticles(600)
txtFileCountInSubdirectories()